### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by LejusVDP** [LejusVDP/STEVE-IS-SUS#3]
### Tasks of Among Us
**Common Tasks**
- [x] Wires task all across the map
- [x] Card Swipe task in Admin

**Long Tasks**
- [x] Scan task in Medbay
- [x] Engine task in Upper and Lower Engine
- [x] Simon Says task in Reactor
- [x] Garbage task in Cafeteria and then Storage
- [x] counterpart of the Garbage task in O2 and then Storage
- [x] Samples task in Medbay
- [x] Refueling task in Storage, Upper and Lower Engine

**Short Tasks**
- [x] Distributor task in Electrical
- [x] Shields task in Shields
- [x] Asteroids task in Weapons
- [x] O2 Filter task in O2
- [x] Course task in Navigation
- [x] Power Diversion task in Electrical
- [x] Steering task in Navigation
- [x] Manifolds task in Reactor
- [x] Download task all across the map
